name: Keep Supabase Alive

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Test réseau
        run: curl -v https://google.com --max-time 10

      - name: Test Supabase sans auth
        run: curl -v https://wqicminuxbixwrdlwhqs.supabase.co --max-time 10
